[package]
name = "serde-pydict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.20.0"
serde = "1.0.190"

[dev-dependencies]
pyo3 = { version = "0.20.0", features = ["auto-initialize"] }
